upgrade: no

app_repo: "https://github.com/dockersamples/linux_tweet_app.git"
doc_root: "/opt/linux_tweet_app"
image_name: "linux_tweet_app:latest"
compose_file: "/opt/linux_tweet_app/docker-compose.yml"
data_directory: "/opt/linux_tweet_app/data"
domain: "sretest.ddns.net"